### PR TITLE
Fix getNdkVersion

### PR DESCRIPTION
**Pull request by kevinresol**
see: http://try.haxe.org/#5601e

### CODE REVIEW

**Comment by hughsando** [comment]
I think that this should probably be "^" (anchor start) like in the other regex, instead of slash.  Does this work for you?

**Comment by kevinresol** [comment]
Without my fix, it doesn't work, because `inDirName` is a full path like `/usr/somewhere/android-ndk/r10b`. So I think a `^` will not work either...

**Comment by hughsando** [comment]
I see, it is using the full path.
Then I think your solution is good, although I would be tempted to add ".*" and the beginning to greedily consume other possible matches and leave just the last.

**Comment by kevinresol** [comment]
I am not very good at regex, how about `$` at the end instead?
e.g. `~/\/(android-ndk-)?r(\d+)*\/?$/;`

**Comment by hughsando** [comment]
I have just put something like this in.  I think the main problem is the star at the end - this allowed it to match against a simple 'r', which is obviously not good.  The slash provides a good anchor as well.

**Comment by hughsando** [comment]
Maybe $ as end would have been good too.  Maybe as well?

**Comment by hughsando** [comment]
Need room for the letter at the end - not sure what the range could be here. [a-z]? maybe

**Comment by hughsando** [comment]
I hope this is working now, so closing.

**Pull request closed without merging**
