### PR TITLE
Fix hxcpp_parse_int to allow + in hex notation

### PR DESCRIPTION
**Pull request by tobil4sk**
Previously this would result in `null`.

### CODE REVIEW

**Comment by Simn** [comment]
CI complains about something that seems related:

```
Test Failed:parsed hex value was not 0, null
Test Failed:parsed hex value was not 0, null
```

Not sure what it's even executing there though...

**Comment by tobil4sk** [comment]
Seems to be coming from here:
https://github.com/HaxeFoundation/hxcpp/blob/master/test/std/Test.hx#L915
https://github.com/HaxeFoundation/hxcpp/blob/master/test/std/Test.hx#L935

For:
```haxe
'   0x'
'   -0x'
```
It's about how it handles an empty hexadecimal prefix. I could change this here to return 0 instead of null fairly easily, but in the Haxe unit tests I ended up leaving these cases unspecified because there are some targets where we cannot change this behaviour without overhead.

**Comment by Simn** [comment]
If hxcpp tests this I would prefer to not change the behavior, even if we leave it unspecified in the official docs.

**Comment by tobil4sk** [comment]
Alright, I'll revert it and I'll make sure it hasn't changed on any other targets either.

**Comment by tobil4sk** [comment]
Should be good now. I've added more tests for good measure.

**Pull request merged**
