### PR TITLE
Topic haxe date

### PR DESCRIPTION
**Pull request by bjitivo**
These are UTC additions that TiVo made to the Date class, to support functionality that we intend to plumb up through the haxe std classes.

### CODE REVIEW

**Comment by Simn** [comment]
This seems to remove some functions in StdLibs.h:

```
C:\projects\hxcpp\test\haxe\bin\include\haxe/ds/WeakMap.h(52) : error C3861: '__object_hash_set': identifier not found 
C:\projects\hxcpp\test\haxe\bin\include\haxe/ds/WeakMap.h(53) : error C3861: '__object_hash_set': identifier not found 
C:\projects\hxcpp\test\haxe\bin\include\haxe/ds/WeakMap.h(54) : error C3861: '__object_hash_set_int': identifier not found 
C:\projects\hxcpp\test\haxe\bin\include\haxe/ds/WeakMap.h(55) : error C3861: '__object_hash_set_int': identifier not found 
C:\projects\hxcpp\test\haxe\bin\include\haxe/ds/WeakMap.h(56) : error C3861: '__object_hash_set_int': identifier not found 
C:\projects\hxcpp\test\haxe\bin\include\haxe/ds/WeakMap.h(57) : error C3861: '__object_hash_set_int': identifier not found 
C:\projects\hxcpp\test\haxe\bin\include\haxe/ds/WeakMap.h(58) : error C3861: '__object_hash_set_int': identifier not found 
C:\projects\hxcpp\test\haxe\bin\include\haxe/ds/WeakMap.h(59) : error C3861: '__object_hash_set_int': identifier not found 
C:\projects\hxcpp\test\haxe\bin\include\haxe/ds/WeakMap.h(60) : error C3861: '__object_hash_set_int': identifier not found 
C:\projects\hxcpp\test\haxe\bin\include\haxe/ds/WeakMap.h(61) : error C3861: '__object_hash_set_float': identifier not found 
C:\projects\hxcpp\test\haxe\bin\include\haxe/ds/WeakMap.h(62) : error C3861: '__object_hash_set_float': identifier not found 
C:\projects\hxcpp\test\haxe\bin\include\haxe/ds/WeakMap.h(63) : error C3861: '__object_hash_set_string': identifier not found 
./src/haxe/ds/WeakMap.cpp(49) : error C2039: '__object_hash_set' : is not a member of '`global namespace'' 
./src/haxe/ds/WeakMap.cpp(49) : error C3861: '__object_hash_set': identifier not found 
./src/haxe/ds/WeakMap.cpp(61) : error C2039: '__object_hash_keys' : is not a member of '`global namespace'' 
./src/haxe/ds/WeakMap.cpp(61) : error C3861: '__object_hash_keys': identifier not found 
Error: error running cl.exe -Iinclude -nologo -Od /WX- /fp:precise -DHX_WINDOWS -D_USING_V1
```

**Comment by bjitivo** [comment]
Sorry, I need to fix these pull requests locally rather than just putting them up and hoping they'll go through.  However after a long, long day of patch wrangling I really just thought I'd get lucky :( ...

**Comment by Simn** [comment]
We have a short readme on running things locally here: https://github.com/HaxeFoundation/haxe/blob/development/tests/README.md

**Comment by bjitivo** [comment]
Failing with the same build failure that is present on master branch.

**Comment by ncannasse** [comment]
@hughsando could you review the changes

**Comment by hughsando** [comment]
I have hand-merged this is, so it is going to need some testing.
I also have not tested on some of the targets yet - eg, iphone.
There was an issue with the format string used in __internal_to_string was not liked by windows, so we might need a more global solution to __hxcpp_to_utc_string.

**Comment by bjitivo** [comment]
Verified that you pulled the changes in manually.  Thanks Hugh!

**Pull request closed without merging**
