### PR TITLE
Semaphores and condition variables.

### PR DESCRIPTION
**Pull request by Apprentice-Alchemist**
See HaxeFoundation/haxe#10503.

### CODE REVIEW

**Comment by Apprentice-Alchemist** [comment]
Condition variables are not supported on Windows XP and earlier.
Should there be a `HXCPP_WINXP_COMPAT` define that disables condition variables?

**Comment by Simn** [comment]
Could you please push again, I'm not sure what our CI is doing and I can't restart it...

**Comment by Apprentice-Alchemist** [comment]
> I'm not sure what our CI is doing

If you're talking about the linux builds failing, that's because Microsoft removed the ubuntu-16.04 images.
See https://devblogs.microsoft.com/devops/hosted-pipelines-image-deprecation/ and #972.

**Comment by Simn** [comment]
I see, thanks for pointing that out. I have merged #972, so we should be able to green this one now.

**Comment by Simn** [comment]
I'll go ahead and assume that the linux failures are random CI nonsense, let's see if this works after merging...

**Pull request merged**
