### PR TITLE
Map toString brackets

### PR DESCRIPTION
**Pull request by RblSb**
Changes brackets style in maps for https://github.com/HaxeFoundation/haxe/pull/9260

### CODE REVIEW

**Comment by hughsando** [comment]
Is the intention here to have Map display differently from Dynamic ?
If you want to restrict it to a particular version (eg, haxe 4.1) there is going to need to be some conditional-compiling in the c++ code.

**Comment by RealyUniqueName** [comment]
The intention is to have Map display the same as in Haxe syntax: `[key => value]`

**Comment by Simn** [comment]
Hmm yeah, updating hxcpp should not cause any printing changes on Haxe versions < 4.3.

**Comment by Simn** [comment]
This looks good to me now that everything is hidden behind an API check.

**Pull request merged**
