### PR TITLE
Topic string churn

### PR DESCRIPTION
**Pull request by bjitivo**
Reduce string churn by adding a comparison function to the String class that compares directly against const char * strings.  Then, don't use HX_CSTRING(xxx) all over the code to compare against static string values, since that macro creates a String class on the stack.  Avoiding this object creation reduces churn.

### CODE REVIEW

**Comment by hughsando** [comment]
HX_CSTRING should be using the inline-constructor ```inline String(const HX_CHAR *inPtr,int inLen)``` to create a stack struct that joins the constant (not copied) pointer with the length.  So there should not be any churn.  Are you detecting allocations in this case?

**Comment by hughsando** [comment]
Actually, I use for example : HX_FIELD_EQ(inName,"main") in the generated code.

**Comment by hughsando** [comment]
... Although I have made sure the length is correct before doing this.

**Comment by bjitivo** [comment]
I can't remember the details of why I thought there was churn involved in these comparisons.  I might have been wrong.

**Comment by bjitivo** [comment]
OK I think my confusion was believing that the HX_CSTRING macro was allocating the strings from the garbage collector instead of the stack.  But on re-read I believe the string objects are being allocated on stack and not using the garbage collector at all.  And furthermore, the constructor is inlined and doesn't really do anything and I expect that the compiled code would be minimal.

If you agree with the above, feel free to reject this pull request.  Thanks!

**Comment by hughsando** [comment]
Cool - I think we are on the same page.

**Pull request closed without merging**
