### PR TITLE
New "overwrite" option in CopyFile.

### PR DESCRIPTION
**Pull request by aW4KeNiNG**
Hi.

I have a large list of "copyFile"s in my build. These files don't change over time and it is really slow when i try to compile the application. So i have added a new "overwrite" option, with "true" by default.

### CODE REVIEW

**Comment by hughsando** [comment]
It might be nice to have a system that checks time stamps (isOutOfDate).  This could probably be on by default, with maybe "alwaysOverwrite" to force overwriting, not mater what the stamp.

**Comment by aW4KeNiNG** [comment]
Maybe the "overwrite" option could be a list of options instead of bool. For example, it can be "always", "never", "only_old_date"... Or something like that. What do you think?

**Comment by hughsando** [comment]
Sound good = "always", "never", "ifNewer"   Currently, the implementation
is "always", so I guess this should be the default to avoid causing
problems.

**Comment by aW4KeNiNG** [comment]
Done :)

**Pull request merged**
