### PR TITLE
Remove at

### PR DESCRIPTION
**Pull request by delahee**
implements removeAt which allows to get rid of those pesky allocation when removing objects in arrays. Cf https://github.com/HaxeFoundation/haxe/issues/4238

### CODE REVIEW

**Comment by delahee** [comment]
@andyli Hi ! the failure is dued to caml dll setup which misses libzip but my PR has nothing to do with this, are you sure build env is ok ?

**Comment by andyli** [comment]
I'm not sure yet. AppVeyor has been annoyingly unstable and I'm still figuring it out and contacting their support about that.

**Comment by delahee** [comment]
@andyli @hughsando hey bros since travis is passing maybe one of you can check out my code and merge so that I can move on :) thx !

**Comment by andyli** [comment]
@hughsando is the one who will review.
I don't have enough cpp knowledge to comment ;)

**Comment by hughsando** [comment]
I have implemented this separately.

**Pull request closed without merging**
