### PR TITLE
Fix: add a basic mapping from haxe -> c++

### PR DESCRIPTION
**Pull request by fzzr-**
e.g.: `int = Int`.
When we build library (with `-D static_link`),
It allows to use it in Xcode-project and safely build.

_Mb. need more types to add._

### CODE REVIEW

**Comment by fzzr-** [comment]
screen shot 2015-01-09 at 18 27 26

**Comment by hughsando** [comment]
I have moved the hxcpp 'Class' to 'hx::Class', so you can compile with objc now.  Does this solve this issue?

**Comment by hughsando** [comment]
I think objc compiling should be good now.  Perhaps start a new issue if there are other concerns.

**Comment by fzzr-** [comment]
Thx. I'll test it soon.

**Pull request closed without merging**
