### PR TITLE
[WinRT] compile fixes

### PR DESCRIPTION
**Pull request by madrazo**
Fix set -ZW ABI. Compiles "nme windows -Dwinrt" (with -ZW). Added note in msvc-toolchain.xml to compile for xboxone uwp
( Fixes https://github.com/HaxeFoundation/hxcpp/issues/442 )

### CODE REVIEW

**Comment by madrazo** [comment]
this one has an error, I am sending another one

**Comment by Gama11** [comment]
Fyi, if you push to the same branch, the pull request gets updated.

**Comment by madrazo** [comment]
Thanks, I am getting the hang of this. I also closed it because I had some "Merge remote-tracking branch 'refs/remotes/HaxeFoundation/master'" so I think that I need to create the branch after updating, or avoid updating from HaxeFoundation in my branch.

**Comment by Simn** [comment]
Since GitHub added the squash-and-merge button it doesn't matter that much anymore, but it's still a good idea to keep clean branches.

**Pull request closed without merging**
