### PR TITLE
Topic gc collect compact

### PR DESCRIPTION
**Pull request by bjitivo**
We need these functions in our own application, so exposing them.

### CODE REVIEW

**Comment by hughsando** [comment]
Not sure about this one.  Since it does not rely on any special types, you can export any function to like from hxcpp back into native code by passing in a closure.

**Comment by underscorediscovery** [comment]
I'd be interested in more fine grained access to gc (Is gc disable is still a nop?) I've not yet gotten to this but I know for sure in future I need to turn off GC at times and I think that access to collect/compact compliments this need as well. 

Do you mean that calling within a closure would have access to the gc calls with untyped __cpp__ ?

**Comment by hughsando** [comment]
I was thinking more about how to export the function to the ndll code, so
from cpp:

myndll_set_gc_runner( function() cpp.vm.Gc.run(true) )
myndll_set_gc_enabler( cpp.vm.Gc.enable )

And then store this closure in the ndll somewhere.

**Comment by underscorediscovery** [comment]
Ah ok, but in my previous tests only run works, does enable work yet? I would use that if I could

**Comment by bjitivo** [comment]
OK, we'll try to find another way to do this.  Feel free to close this pull request.

**Pull request closed without merging**
