### PR TITLE
Topic debugger deadlock

### PR DESCRIPTION
**Pull request by bjitivo**
Fixes a debugger deadlock that occurs when user code is run when the debugger evaluates expressions that run property accessor/mutator functions, and that user code throws an exception.  The debugger thread would then try to break into the debugger thread, which would deadlock.

### CODE REVIEW

**Comment by Simn** [comment]
This fails on our CI:

```
g++ -o Test-debug -debug -rdynamic -m64 @obj/linux64-debug//all_objs -lpthread -ldl -ldl
obj/linux64-debug/86e7994f_Debug.o: In function `hx::NullReference(char const*, bool)':
/home/travis/build/HaxeFoundation/hxcpp/src/hx/Debug.cpp:1990: undefined reference to `__hxcpp_dbg_checkedThrow(Dynamic)'
collect2: ld returned 1 exit status
Error: error running g++ -o Test-debug -debug -rdynamic -m64 @obj/linux64-debug//all_objs -lpthread -ldl -ldl
Error: Build failed
```

**Comment by bjitivo** [comment]
Sorry, I'll fix it.  I apologize for the bad state of some of these pull requests, it was really hard to extricate a bunch of changes from our Perforce change history over the past couple of years into git and then into individual pull requests, especially given that our version of hxcpp is a little older and some by hand patching had to be done.  I am not familiar with the unit test workflow of hxcpp/haxe but I will try to make sure these changes pass in a local build today and apply necessary fixes here.  Thank you for your patience!

**Comment by bjitivo** [comment]
This change has been fixed and rebased to top of trunk and now the build is passing.  We recommend taking this pull request as it fixes a debugger deadlock.  Thanks!

**Comment by bjitivo** [comment]
Urgh, I screwed up.  Just going to cancel this and start over.

**Pull request closed without merging**
